spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: zt-web
          uri: http://www.s98k.com
          predicates:
          - Path=/report/**