server:
  port: 8000

#数据源配置
spring:
  application:
    name: zt-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url:  jdbc:mysql://192.168.1.249:3306/mall_new5?useUnicode=true&characterEncoding=utf-8
    # url:  jdbc:p6spy:mysql://192.168.1.249:3306/mall_new5?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234567

#配置日志地址
logging:
  level:
    com.zt.dao.mapper: debug

#关闭banner
mybatis-plus:
  global-config:
    banner: false