server:
  port: 8080

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url:  jdbc:mysql://192.168.1.249:3306/mall_new5?useUnicode=true&characterEncoding=utf-8
    # url:  jdbc:p6spy:mysql://192.168.1.249:3306/mall_new5?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234567
